### ISSUE TITLE
SSL method in Android 2.2

### ISSUE THREAD

**Issue by adre310** [foxykeep/DataDroid#33]
In NetworkConnectionImpl 

SSLContext sc = SSLContext.getInstance("SSL");
but in android 2.2 (API 8) - i have exception SSLMethodUnknown
more valid

SSLContext sc = SSLContext.getInstance("TLS");

**Comment by foxykeep** [comment]
So ... I tried on my 2.2 device and on a 2.2 emulator and I don't have any issue with it.

Is it on a specific device ?

**Comment by adre310** [comment]
On 29.05.2013 9:52, Foxykeep wrote:

> So ... I tried on my 2.2 device and on a 2.2 emulator and I don't have 
> any issue with it.
> 
> Is it on a specific device ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/foxykeep/DataDroid/issues/33#issuecomment-18597429.
> 
> if line 293 to in NetworkConnectionImpl.java
>              SSLContext sc = SSLContext.getInstance("SSL");

## i have exception

LogCat
05-29 11:44:24.252      289-317/iae.home.money2011.v2 
E/NetworkConnectionImpl: NoSuchAlgorithmException
         java.security.NoSuchAlgorithmException: SSLContext SSL 
implementation not found
         at 
org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:105)
         at javax.net.ssl.SSLContext.getInstance(SSLContext.java:58)
         at 
com.foxykeep.datadroid.internal.network.NetworkConnectionImpl.getAllHostsValidSocketFactory(NetworkConnectionImpl.java:293)
         at 
com.foxykeep.datadroid.internal.network.NetworkConnectionImpl.execute(NetworkConnectionImpl.java:188)
         at 
com.foxykeep.datadroid.network.NetworkConnection.execute(NetworkConnection.java:221)
         at 
iae.home.money2011.v2.sync.adapter.SyncAdapter.onPerformSync(SyncAdapter.java:62)
         at 
android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:163)
05-29 11:44:24.252      289-317/iae.home.money2011.v2 E/SyncAdapter: 
onPerformSync
         com.foxykeep.datadroid.exception.ConnectionException: 
java.security.NoSuchAlgorithmException: SSLContext SSL implementation 
not found
         at 
com.foxykeep.datadroid.internal.network.NetworkConnectionImpl.execute(NetworkConnectionImpl.java:262)
         at 
com.foxykeep.datadroid.network.NetworkConnection.execute(NetworkConnection.java:221)
         at 
iae.home.money2011.v2.sync.adapter.SyncAdapter.onPerformSync(SyncAdapter.java:62)
         at 
android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:163)
         Caused by: java.security.NoSuchAlgorithmException: SSLContext 
SSL implementation not found
         at 
org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:105)
         at javax.net.ssl.SSLContext.getInstance(SSLContext.java:58)
         at 
com.foxykeep.datadroid.internal.network.NetworkConnectionImpl.getAllHostsValidSocketFactory(NetworkConnectionImpl.java:293)
         at 
com.foxykeep.datadroid.internal.network.NetworkConnectionImpl.execute(NetworkConnectionImpl.java:188)

##          ... 3 more

but if this line is
             SSLContext sc = SSLContext.getInstance("TLS");

run fine.

device google sdk
